//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Configuration;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Security;
using System.Web.UI.WebControls.WebParts;
using System.Collections.Generic;
using System.Web.DynamicData;
using System.Collections.Specialized;
using System.Xml.Linq;
using System.Collections;
using System.Linq;
using System.Web.UI;
using System.Web.Profile;
using System.Text;
using System.Web.UI.HtmlControls;
using System.Web.Caching;
using System;
using System.Web.UI.WebControls;
using System.Web.SessionState;
using System.ComponentModel.DataAnnotations;

public class viewstationery_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
}
}
